server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/pablomunozramirez/PEP_2
          search-paths: "Aplicación-microservicio-avanzado-postgresql/config-data"