apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  #base de dato Cuotas
  POSTGRES_DB_CUOTAS: topeducationcuotas
  #base de dato Estudiantes
  POSTGRES_DB_ESTUDIANTES: topeducationestudiantes
  #base de dato Planilla
  POSTGRES_DB_PLANILLA: topeducationplanillas